name: ${project.name}
version: ${project.version}
main: co.odsilvert.dsmz.main.DSMZ
authors: [Silver, ODST]
description: A test plugin for merging all existing features
api-version: 1.12
depend: [ProtocolLib]
